# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

stages:
  - stage: Build
    jobs:
    - job: Building_Artifact
      steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: '**/*.war'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'warfile'
  - stage: Release
    jobs:
      - job: Deploy
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'warfile'
            downloadPath: '$(System.ArtifactsDirectory)'
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              cd $(System.ArtifactsDirectory)
              ls
              cd warfile
              ls
        # - task: TomcatDeployment@1
        #   inputs:
        #     TomcatUrl: 'http://20.124.246.229:8080/'
        #     Username: 'admin'
        #     Password: 'admin'
        #     Warfile: '$(System.ArtifactsDirectory)/warfile/webapp-0.0.1-SNAPSHOT.war'
        #     Context: '/'
        #     ServerVersion: '7OrAbove'